### ISSUE TITLE
Found a difficulty compiling api.cpp with Boost 1.74.0

### ISSUE THREAD

**Issue by IvanMontillaM** [niXman/binapi#1]
Good morning @niXman,

When I got to compile the websockets example, I copied the `boost` directory inside `include` directory. The `boost` library version I was using is `1.74.0`.

Lines `335`, `340`, `345`, `406` and `411` of `api.cpp` I had to patch as the following line: `auto body_size = std::to_string(data.size());`

I don't know if it's the elegant solution (probably not!), but compiles without warnings to me.

If I don't do this, I get the following error:
`error: no matching function for call to ‘boost::beast::http::message<true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >::set(boost::beast::http::field, long unsigned int&)’`
`413 |             m_req.set(boost::beast::http::field::content_length, body_size);`

By the way: Thank you for such a great library, looking forward to use it more! 👍🏼

**Comment by niXman** [comment]
yes, you are right!

the signature of the `boost::beast::http::message::set()` was changed. will fix, thanks!

**Comment by niXman** [comment]
[done](https://github.com/niXman/binapi/commit/242c5e3218f3ed643bb4d1ed5dc9c26474726bdd)

closed.
