### ISSUE TITLE
[SOLVED] Building example error: "BOOST_CXX14_CONSTEXPR’ does not name a type"...  and others errors

### ISSUE THREAD

**Issue by bashman** [niXman/binapi#13]
Hi. I am trying to compile binapi but I get this errors:

et_ops.hpp:370:8: error: ‘BOOST_CXX14_CONSTEXPR’ does not name a type; did you mean ‘BOOST_MP_CXX14_CONSTEXPR’
et_ops.hpp:645:8: error: ‘BOOST_CXX14_CONSTEXPR’ does not name a type; did you mean ‘BOOST_MP_CXX14_CONSTEXPR’
bulk_guarantee.hpp:941:10: error: ‘BOOST_ASIO_CONSTEXPR’ does not name a type; did you mean ‘BOOST_STATIC_CONSTEXPR’

And many others. 

Boost 1.75.0 (buided in my machine) --> The build and install  was successful. 
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Some advice?

**Comment by niXman** [comment]
hi,

try to update GCC to any 9.x.x version.

**Comment by bashman** [comment]
Solution:

1. add ppa for a more updated gcc ( in my case 9.xxx)
`add-apt-repository ppa:ubuntu-toolchain-r/test && apt update &&  apt install gcc-9`
2. Uninstall old cmake version and install latest from source
3. add ppa for latest libboost
`add-apt-repository ppa:mhier/libboost-latest  && apt install libboost1.74-dev libboost1.74`

Enjoy. 

![imagen](https://user-images.githubusercontent.com/1690516/108633137-a29f2600-7440-11eb-85a8-49c00203c0d8.png)
