### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by repane4229** [niXman/binapi#14]
Can you please update the git/cmake so it includes the needed libs for this to work.
It is really hard to get it all to work with all the libs

**Comment by niXman** [comment]
hi,

I'm sorry but I don't have any windows device :(

**Comment by repane4229** [comment]
you can easy install windows on a virtual machine for free

**Comment by niXman** [comment]
I don't see the point in doing this because it will take too much of my time.
especially considering that you have already been answered by the user who solved this issue: https://github.com/niXman/binapi/issues/7
