### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by gitkornel** [niXman/binapi#17]
So when trying to use the API I get these errors:

1>C:\Users\Administrator\Desktop\Binance_cpp\API\enums.cpp(12,10): fatal error C1083: Cannot open include file: 'enums.hpp': No such file or directory
1>errors.cpp
1>C:\Users\Administrator\Desktop\Binance_cpp\API\errors.cpp(12,10): fatal error C1083: Cannot open include file: 'errors.hpp': No such file or directory
1>io_state.cpp
1>pairslist.cpp
1>reports.cpp
1>tools.cpp
1>types.cpp
1>websocket.cpp
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(49,43): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(49,14): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(49,14): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(49,13): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(49,70): error C2146: syntax error: missing '>' before identifier 'ptr'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(49,13): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(53,27): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(53,34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(53,34): error C2143: syntax error: missing ',' before '&'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(74,15): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(72,20): error C2061: syntax error: identifier 'string'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(76,38): error C2143: syntax error: missing ')' before '{'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(72,20): error C2059: syntax error: ')'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(83,82): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(83,53): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(83,53): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(83,52): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(83,52): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(87,82): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(87,53): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(87,53): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(87,52): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(87,52): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(92,82): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(92,53): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(92,53): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(92,52): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(92,52): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(96,86): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(96,57): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(96,57): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(96,56): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(96,56): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(100,83): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(100,54): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(100,54): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(100,53): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(100,53): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(104,84): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(104,55): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(104,55): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(104,54): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(104,54): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(108,81): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(108,52): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(108,52): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(108,51): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(108,51): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(112,82): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(112,53): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(112,53): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(112,52): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(112,52): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(115,80): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(115,51): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(115,51): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(115,50): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(115,50): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(116,82): error C2039: 'string': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(116,53): error C2143: syntax error: missing ')' before 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(116,53): error C2059: syntax error: 'const'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(116,52): error C2065: 'string': undeclared identifier
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(116,52): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(61,29): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(61,1): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(61,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(61,1): message : '_Ty=binapi::ws::websocket::on_message_received_cb &'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(61,29): error C2119: 'cb': the type for 'auto' cannot be deduced from an empty initializer
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(64,48): error C2064: term does not evaluate to a function taking 5 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(68,1): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'binapi::ws::websocket::impl::async_start::<lambda_245b28ba83cb1bddcc7faf0e2447ec96>'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(68,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(76,29): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(76,1): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(76,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(76,1): message : '_Ty=binapi::ws::websocket::on_message_received_cb &'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(76,29): error C2119: 'cb': the type for 'auto' cannot be deduced from an empty initializer
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(79,48): error C2064: term does not evaluate to a function taking 5 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(83,1): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'binapi::ws::websocket::impl::async_connect::<lambda_53986ba2f740abf48f39e700021564ff>'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(83,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(102,29): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(102,1): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(102,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(102,1): message : '_Ty=binapi::ws::websocket::on_message_received_cb &'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(102,29): error C2119: 'cb': the type for 'auto' cannot be deduced from an empty initializer
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(105,48): error C2064: term does not evaluate to a function taking 5 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(109,1): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'binapi::ws::websocket::impl::on_connected::<lambda_e227cfc09cde88c68d3799fffa86fd56>'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(109,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(100,26): error C2672: 'boost::asio::ssl::stream<boost::asio::ip::tcp::socket>::async_handshake': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(110,1): error C2780: 'auto boost::asio::ssl::stream<boost::asio::ip::tcp::socket>::async_handshake(boost::asio::ssl::stream_base::handshake_type,const ConstBufferSequence &,BufferedHandshakeHandler &&)': expects 3 arguments - 1 provided
1>C:\vcpkg\installed\x64-windows-static\include\boost\asio\ssl\stream.hpp(491): message : see declaration of 'boost::asio::ssl::stream<boost::asio::ip::tcp::socket>::async_handshake'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(110,1): error C2780: 'auto boost::asio::ssl::stream<boost::asio::ip::tcp::socket>::async_handshake(boost::asio::ssl::stream_base::handshake_type,HandshakeHandler &&)': expects 2 arguments - 1 provided
1>C:\vcpkg\installed\x64-windows-static\include\boost\asio\ssl\stream.hpp(455): message : see declaration of 'boost::asio::ssl::stream<boost::asio::ip::tcp::socket>::async_handshake'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(116,29): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(116,1): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(116,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(116,1): message : '_Ty=binapi::ws::websocket::on_message_received_cb &'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(116,29): error C2119: 'cb': the type for 'auto' cannot be deduced from an empty initializer
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(118,1): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'binapi::ws::websocket::impl::on_async_ssl_handshake::<lambda_62f07e8f396e4a7d8eec4290f2eb1cb4>'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(118,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(113,13): error C2672: 'boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>,true>::async_handshake': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(119,1): error C2893: Failed to specialize function template 'auto boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>,true>::async_handshake(boost::beast::string_view,boost::beast::string_view,HandshakeHandler &&)'
1>C:\vcpkg\installed\x64-windows-static\include\boost\beast\websocket\stream.hpp(883): message : see declaration of 'boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>,true>::async_handshake'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(119,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(119,1): message : 'HandshakeHandler=void'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(144,40): error C2064: term does not evaluate to a function taking 5 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(151,29): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(151,1): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(151,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(151,1): message : '_Ty=binapi::ws::websocket::on_message_received_cb &'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(151,29): error C2119: 'cb': the type for 'auto' cannot be deduced from an empty initializer
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(153,1): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'binapi::ws::websocket::impl::start_read::<lambda_6d1677d997dfe74f95cc09ec9109d126>'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(153,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(149,13): error C2672: 'boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>,true>::async_read': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(154,1): error C2893: Failed to specialize function template 'auto boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>,true>::async_read(DynamicBuffer &,ReadHandler &&)'
1>C:\vcpkg\installed\x64-windows-static\include\boost\beast\websocket\stream.hpp(1933): message : see declaration of 'boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>,true>::async_read'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(154,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(154,1): message : 'DynamicBuffer=boost::beast::multi_buffer'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(154,1): message : 'ReadHandler=void'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(158,40): error C2064: term does not evaluate to a function taking 5 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(174,19): error C2064: term does not evaluate to a function taking 5 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(178,58): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(178,1): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(178,1): message : With the following template arguments:
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(178,1): message : '_Ty=binapi::ws::websocket::on_message_received_cb &'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(178,1): error C2660: 'binapi::ws::websocket::impl::start_read': function does not take 2 arguments
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(142,10): message : see declaration of 'binapi::ws::websocket::impl::start_read'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(204,1): error C2511: 'void binapi::ws::websocket::start(const std::string &,const std::string &,const std::string &,binapi::ws::websocket::on_message_received_cb,binapi::ws::websocket::holder_type)': overloaded member function not found in 'binapi::ws::websocket'
1>C:\Users\Administrator\Desktop\Binance_cpp\include\binapi\websocket.hpp(44): message : see declaration of 'binapi::ws::websocket'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(204,54): error C2672: 'std::move': no matching overloaded function found
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(204,61): error C2893: Failed to specialize function template 'remove_reference<_Ty>::type &&std::move(_Ty &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits(1454): message : see declaration of 'std::move'
1>C:\Users\Administrator\Desktop\Binance_cpp\API\websocket.cpp(204,61): fatal error C1003: error count exceeds 100; stopping compilation

My lib includes:
zlib.lib
cryptopp-static.lib
libcrypto.lib
libssl.lib
pthreadVC3.lib
pthreadVCE3.lib
pthreadVSE3.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib

And my preprocess:
CURL_STATICLIB
_CRT_SECURE_NO_WARNINGS
_SILENCE_CXX17_STRSTREAM_DEPRECATION_WARNING
_WIN32_WINDOWS
DTF_HEADER_ONLY
__FLATJSON__CHILDS_TYPE=std::uint32_t
__FLATJSON__VLEN_TYPE=std::uint32_t

I'm on Windows x64

**Comment by niXman** [comment]
please re-clone the repo again and provide me the output.
because many people were able to successfully build this project and I do not understand why you are having these problems...

**Comment by gitkornel** [comment]
> please re-clone the repo again and provide me the output.
> because many people were able to successfully build this project and I do not understand why you are having these problems...

Still doesn't work, bunch of errors and it just doesn't work.

There's so many that my VS crashed when trying to compile, could you please upload or send me your project that I can try to build?

**Comment by niXman** [comment]
hi,

I'm sorry but I have no any windows device but you can see this: https://github.com/niXman/binapi/issues/7
