### ISSUE TITLE
Need some docs or maybe guides.

### ISSUE THREAD

**Issue by VladslavAlex** [niXman/binapi#20]
Thank you for your job.
Hello!
I  am a novice in c++, with some python skills. I need to write a high frequency trading bot trying your api.
-my bot should listen websocket with minimal input lags;
-then perform several trades in async or parrallel way;
-then listen to websockets;
-then trades;
and so on...))
 Could you please help me with my task?
Thank you in advance.

**Comment by niXman** [comment]
hi,

with such questions you should address to any forum.

**Comment by VladslavAlex** [comment]
Thank you for reply!
I would like to use your code. Could you please help me with some template code for my task?

**Comment by niXman** [comment]
hi,

> Could you please help me with some template code using your binapi for my task

could you please look for examples dir?

closed.
