### ISSUE TITLE
Low price precision precision in BTCUSDT

### ISSUE THREAD

**Issue by VladslavAlex** [niXman/binapi#21]
Trying my best  with c++ and your library :))
In websocket,cpp example
Only one digit after point is in BTC trading pairs: 
trades: {"E":1615015780440,"s":"BTCUSDT","t":687090517,"p":"49035.6","q":"0.0007","b":5116638152,"a":5116638249,"T":1615015780439,"m":true,"M":true}

so price in bids and asks is the same:
book: {"u":9311715174,"s":"BTCUSDT","b":"49035.6","B":"0.002208","a":"49035.6","A":"0.497945"}
It looks like should be at least one more digit(from standard websocket bookTicker payload):
{
	"A" : "2.39395300",
	"B" : "0.00886500",
	"a" : "48898.95000000",
	"b" : "48898.94000000",
	"s" : "BTCUSDT",
	"u" : 9312263811
}
Thanks

**Comment by niXman** [comment]
hi,

back to my question of what type are the variables `a` and `b` ?

**Comment by VladslavAlex** [comment]
I don't know. it was the output of websockets example in the library

**Comment by niXman** [comment]
> I don't know.

then I think with such the question you should address to any forum.
