### ISSUE TITLE
Error when using user_data_stream websocket

### ISSUE THREAD

**Issue by Gustavobbr** [niXman/binapi#22]
Hi there,

when using the user_data_stream websocket, somehow after the msg arriving, i've got an error and the program terminates.

Following the code :

`    
    auto listenkey = api.start_user_data_stream();

    auto user_data_stream = ws.userdata(listenkey.v.listenKey.c_str(),
         [](const char *fl, int ec, std::string errmsg, binapi::userdata::order_update_t msg) -> bool {
             if ( ec ) {
                 std::cout << "order update: fl=" << fl << ", ec=" << ec << ", errmsg: " << errmsg << ", msg: " << msg << std::endl;
                 return false;
             }

             std::cout << "order update:\n" << msg << std::endl;
             return true;
         }
        ,[](const char *fl, int ec, std::string errmsg, binapi::userdata::account_update_t msg) -> bool {
             if ( ec ) {
                 std::cout << "account update: fl=" << fl << ", ec=" << ec << ", errmsg: " << errmsg << ", msg: " << msg << std::endl;
                 return false;
             }

             std::cout << "account update:\n" << msg << std::endl;
             return true;
         }
    );`

The terminal, with the error at the end : 
order update:
{"e":"executionReport","E":1615052052022,"s":"ADAUSDT","c":"web_fa43c0c8432a405f9755a92aa242ae80","S":"SELL","o":"LIMIT","f":"GTC","q":"5.5","p":"2.10346","P":"0","F":"0","C":"web_66203c7407d54c6a80b7a44ebfe4579a","x":"CANCELED","X":"CANCELED","r":"NONE","i":1077512227,"l":"0","z":"0","L":"0","n":"0","N":"","T":1615052052021,"t":18446744073709551587,"I":2244354641,"w":false,"m":false,"M":false,"O":1615051906682,"Z":"0"}
/home/gustavo/binapi/src/websocket.cpp(271): /home/gustavo/binapi/examples/websockets/../../include/binapi/flatjson.hpp(1397): key not found
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-7i2o53l6.ole" 1>"/tmp/Microsoft-MIEngine-Out-1edzuah8.z09"

**Comment by niXman** [comment]
hmm...
can't confirm. this example works as it should:
```
    static const char json[] = R"({"e":"executionReport","E":1615052052022,"s":"ADAUSDT","c":"web_fa43c0c8432a405f9755a92aa242ae80","S":"SELL","o":"LIMIT","f":"GTC","q":"5.5","p":"2.10346","P":"0","F":"0","C":"web_66203c7407d54c6a80b7a44ebfe4579a","x":"CANCELED","X":"CANCELED","r":"NONE","i":1077512227,"l":"0","z":"0","L":"0","n":"0","N":"","T":1615052052021,"t":18446744073709551587,"I":2244354641,"w":false,"m":false,"M":false,"O":1615051906682,"Z":"0"})";
    binapi::userdata::order_update_t res = binapi::userdata::order_update_t::parse(json, sizeof(json)-1);
```

**Comment by niXman** [comment]
I need more info.

**Comment by Gustavobbr** [comment]
The error was not when parsing, actually is parsed correctly :
![image](https://user-images.githubusercontent.com/37227910/110220344-c2eccd00-7ea3-11eb-8c9d-0130bdde7636.png)


going, step by step, the error were printed when acessing the scheduler.ipp, at the image below, if I go to the next step, the error pops out at the terminal
![image](https://user-images.githubusercontent.com/37227910/110220570-32af8780-7ea5-11eb-9d39-d795899c026f.png)

**Comment by niXman** [comment]
> The error was not when parsing, actually is parsed correctly

why do you say that?
before you gave me this error: `/home/gustavo/binapi/src/websocket.cpp(271): /home/gustavo/binapi/examples/websockets/../../include/binapi/flatjson.hpp(1397): key not found`

this means there is a problem with the parsing.
or don't you get this error anymore?

**Comment by Gustavobbr** [comment]
The problem persists

This problem is the same as the other issue that os opened, #16 .

we can see at the end of the reply from 'bashman' the same error, at the same method :
`/home/lucy/cpp_agent/src/websocket.cpp(270): /home/lucy/cpp_agent/include/binapi/flatjson.hpp(1397): key not found

`

**Comment by niXman** [comment]
> The problem persists

good!
then we agree that the problem is with parsing? I think yes.

then please change [this](https://github.com/niXman/binapi/blob/master/src/websocket.cpp#L440) line like this:
`userdata::account_update_t res; // = userdata::account_update_t::parse(msg.data.c_str(), msg.data.length());`
and start your program. if the error disappears - stop the program and set a breakpoint on that line, start again, and when it triggers - show me the contents of `msg.data`.

**Comment by Gustavobbr** [comment]
I think i was a little misunderstood and I'm sorry for that.
My knowledge in C++ is pretty basic, so, I wasn't trying to point out that you were mistake(and turns out you were right), I was trying to collect data so you could have a better diagnose.

Ok, so for the issue :

I've change as you instructed and the error disappeared

msg.data from IDE
"{\"e\":\"outboundAccountPosition\",\"E\":1615079064879,\"u\":1615079064878,\"B\":[{\"a\":\"BNB\",\"f\":\"0.00026446\",\"l\":\"0.00000000\"},{\"a\":\"USDT\",\"f\":\"0.00755300\",\"l\":\"10.19200000\"},{\"a\":\"ADA\",\"f\":\"2.90000000\",\"l\":\"0"....

cout : msg.data.c_str()
{"e":"outboundAccountPosition","E":1615080067769,"u":1615080067769,"B":[{"a":"BNB","f":"0.00026446","l":"0.00000000"},{"a":"USDT","f":"0.00755300","l":"10.19200000"},{"a":"ADA","f":"2.90000000","l":"0.00000000"}]}

**Comment by niXman** [comment]
got it, thanks.
I'll fix it soon.

**Comment by niXman** [comment]
fixed: https://github.com/niXman/binapi/commit/300261820055f23af9d9d7102a912ed4bacae1d8

please test it.

note: support for `ListStatus` type of payload for `order-update` has not yet been implemented: https://github.com/binance/binance-spot-api-docs/blob/master/user-data-stream.md#order-update

**Comment by Gustavobbr** [comment]
I've tested it and it has been fixed, thank you
