### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by JiangZhengok** [niXman/binapi#23]
```
~/binapi/src/api.cpp:444:9:   required from here
~/binapi/src/api.cpp:443:26: error: cannot call member function ‘void binapi::rest::api::impl::on_connect(const boost::system::error_code&, binapi::rest::api::impl::request_ptr, binapi::rest::api::impl::ssl_socket_ptr)’ without object
              { on_connect(ec, std::move(req), std::move(ssl_socket)); }
```
![image](https://user-images.githubusercontent.com/34699594/110439682-b5795200-80f2-11eb-9837-25f810b285b1.png)

**Comment by niXman** [comment]
which GCC version are you using?

**Comment by JiangZhengok** [comment]
> which GCC version are you using?

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by niXman** [comment]
please close this issue.
