### ISSUE TITLE
How to set proxy?

### ISSUE THREAD

**Issue by JiangZhengok** [niXman/binapi#24]
I am from China, so I can't access binance. I want to know how to set proxy.

**Comment by niXman** [comment]
I didn’t have such a goal of maintaining a proxy, so I can only recommend using a VPN.

**Comment by JiangZhengok** [comment]
> I had no goal of supporting a proxy, so I can only recommend using a VPN.

I have a VPN and I can access binance by firefox browser, but I don't know how to access binance in your project(binapi).
I wish you can help me.

**Comment by niXman** [comment]
> I have a VPN and I can access binance by firefox browser, but I don't know how to access binance in your project(binapi).

if you use a VPN on your device, then all traffic from this device will go through the VPN.

**Comment by niXman** [comment]
@JiangZhengok close please.
