### ISSUE TITLE
double_type issue

### ISSUE THREAD

**Issue by gitkornel** [niXman/binapi#25]
I noticed that the balance output is screwed.

```
static const char *crypto_pair = "BTCUSDT";
auto price = api.price(crypto_pair);

auto balance = api.account_info();

std::cout << balance.v.get_balance("BTC").free << std::endl;
std::cout << price.v << std::endl;
```

Ouput:
```
2.4e-07
{"symbol":"BTCUSDT","price":"54569.7"}
```

The price number is ok but the balance isn't but the code behind it is the same, any ideas how to fix that?

**Comment by niXman** [comment]
https://en.cppreference.com/w/cpp/io/ios_base/precision
https://en.cppreference.com/w/cpp/io/ios_base/flags
