### ISSUE TITLE
Pass parameters to WebSocket streams

### ISSUE THREAD

**Issue by thunderquiet** [niXman/binapi#26]
Hi, 

How would I provide parameters to the WebSocket routes? For example, in the depth calls I would like to specify the depth and update speed. 

Thank you.

**Comment by niXman** [comment]
hi,

I'm not sure if I understood you correctly... please explain.

**Comment by thunderquiet** [comment]
According to the documentation: https://binance-docs.github.io/apidocs/delivery/en/#diff-book-depth-streams
The stream supports `depth` and `update frequency` parameters. ex: `<symbol>@5@100ms`. If I try appending those to the symbol string in my code, I get back nothing, so presumably those need to be passed in some other way?

Thank you for helping out.

**Comment by niXman** [comment]
ah, got it.

I think need to change [this](https://github.com/niXman/binapi/blob/master/include/binapi/websocket.hpp#L85) member-fn as `handle depth(const char *pair, std::size_t ms, on_depth_received_cb cb);` and check the `ms` argument for 100/250/500, and according to the `ms` value change the second argument [here](https://github.com/niXman/binapi/blob/master/src/websocket.cpp#L370).

can you make the necessary changes as PR?

**Comment by niXman** [comment]
hmm...

strange, but [there](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#diff-depth-stream) are different values...

**Comment by thunderquiet** [comment]
Thanks for the tips. Created PR - https://github.com/niXman/binapi/pull/27

Not sure if it makes sense to make the parameter enum instead of size_t to enforce valid values. For example if user provides `600` they will get back nothing.

**Comment by niXman** [comment]
great, thanks!

but two points.

1) have you checked which values are correct? 100/250/500/1000 ?
2) yes I think be better to add enum.
