### ISSUE TITLE
Assertion failed: is_result_responce_type()

### ISSUE THREAD

**Issue by gitkornel** [niXman/binapi#29]
Hello, I'm getting this error, tried to fix it but nothing worked.

Best Regards.

Error: `Assertion failed: is_result_responce_type(), file C:\Users\admin\Desktop\binance\source\API\include\binapi\types.hpp, line 510`

Also, I found out `market_buy_order.v.get_responce_full().price` is always 0 for some reason.

Code:
```
std::string final_coin_name = coin_name + "BTC";
auto market_buy_order = api.new_order(
	final_coin_name.c_str(),
	binapi::e_side::buy,
	binapi::e_type::market,
        binapi::e_time::GTC,
	quantity.c_str(),
	nullptr,
	nullptr,
	nullptr,
	nullptr
	);

std::cout << market_buy_order.v.get_responce_full().price << std::endl;
std::cout << market_buy_order.v.get_responce_result().price << std::endl;
```

**Comment by niXman** [comment]
hi,

ah, this is because `newOrderRespType` hardcoded as `FULL` [here](https://github.com/niXman/binapi/blob/master/src/api.cpp#L793).
I need to think how to do this better...

**Comment by niXman** [comment]
fixed in `mster`: https://github.com/niXman/binapi/commit/73cf3e322430c8b37be556fa8cb6d507fdb711e4

test it please.

**Comment by niXman** [comment]
@gitkornel any news?

**Comment by gitkornel** [comment]
> 
> 
> @gitkornel any news?

hello, still zero.

**Comment by gitkornel** [comment]
`market_buy_order.v.get_responce_result().price`

is always 0 for some reason

**Comment by niXman** [comment]
please provide me server reply.
