### ISSUE TITLE
Hi everyone!

### ISSUE THREAD

**Issue by nikolay-code** [niXman/binapi#3]
Can you please give me some recommendations to build application?
I use:
Debian 9, QT, cmake version 3.18.4,
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
g++ -dumpversion
6.3.0
Boost 1_74
Can you please tell us the steps to build the application?
Which compiler (and version) and OS do you use?
![Screenshot_2020-10-13_04-11-44](https://user-images.githubusercontent.com/60795158/95834047-71804d80-0d0a-11eb-9ac8-05867979e043.png)
![Screenshot_2020-10-13_04-20-09](https://user-images.githubusercontent.com/60795158/95834806-6974dd80-0d0b-11eb-88f0-1b6a97ff19ca.png)

**Comment by niXman** [comment]
try to add `#include <cstring>` into line 18 and let me know.

**Comment by nikolay-code** [comment]
As I see, it doesn't help
![Screenshot_2020-10-13_05-07-42](https://user-images.githubusercontent.com/60795158/95840403-13576880-0d12-11eb-9c4d-0f38f7ffda5e.png)

**Comment by nikolay-code** [comment]
I will try to update gcc to 9.3.0 version, but I'm not sure whether it helps.

**Comment by niXman** [comment]
> try to add #include <cstring> into line 18 and let me know.

file `invoker.hpp`

**Comment by nikolay-code** [comment]
strstr has gone away, but I still have binapi/src/api.cpp|131|error: ‘api’ has not been declared
![Screenshot_2020-10-13_05-27-44](https://user-images.githubusercontent.com/60795158/95842695-d93b9600-0d14-11eb-9aea-ec86bca68b51.png)

**Comment by niXman** [comment]
very strange =)

try to switch to GCC version 9.3.0

**Comment by nikolay-code** [comment]
Anyway, thank you very much!

**Comment by niXman** [comment]
@nikolay-code please close this issue when you solved it.

**Comment by nikolay-code** [comment]
Thank you
