### ISSUE TITLE
Invalid symbol from new_order/new_test_order

### ISSUE THREAD

**Issue by lucyn9** [niXman/binapi#30]
https://github.com/niXman/binapi/blob/4851cd30cd38c331bdd1fd6a29d295db49f6abe5/main.cpp#L179

I was able to compile and run the main example. But when I uncomment the new_order section, it broke on error and printed "invalied symbol" msg for all the pairs I tried. Is that expected at this point?

**Comment by niXman** [comment]
did you use valid private and public keys on the command line?

**Comment by niXman** [comment]
also I hope you specified the valid value in this line: https://github.com/niXman/binapi/blob/4851cd30cd38c331bdd1fd6a29d295db49f6abe5/main.cpp#L186
