### ISSUE TITLE
!ticker@arr stream ends with end of file errmsg.

### ISSUE THREAD

**Issue by alexpitek** [niXman/binapi#31]
Hi, there.
I have an issue while running markets_tickers:
markets(): fl=C:\_BINANCE\_SOFT\binapi-master\src\websocket.cpp(148), ec=2, errmsg: End of file, msg: [].
The message appears ALWAYS though in arbitrary periods (seems depending on internet throughput).
It may work for hours (It went 6 hour in one test) but eventually always fails.
It maybe due to huge amount of data sent every second via socket.
Can you provide !miniTicker@arr stream additionally  with less data to pass the stream?
Thanks for your efforts and excellent code.

**Comment by niXman** [comment]
hi,

> It maybe due to huge amount of data sent every second via socket.

I think yes.

> Can you provide !miniTicker@arr stream additionally with less data to pass the stream?

sure. will do this week.

**Comment by alexpitek** [comment]
thanks

**Comment by niXman** [comment]
done.

- [Individual Symbol Mini Ticker Stream](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#individual-symbol-mini-ticker-stream) -> `websockets::mini_ticker()`
- [All Market Mini Tickers Stream](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#all-market-mini-tickers-stream) -> `websockets::mini_tickers()`

please close the issue.
