### ISSUE TITLE
types.cpp 1394-1398 my_trade_info_t::construct': must return a value

### ISSUE THREAD

**Issue by alexpitek** [niXman/binapi#32]
Hi niXman!
Encountered the following issue:
error C4716: 'binapi::rest::my_trades_info_t my_trade_info_t::construct': must return a value

types.cpp 
lines 1394-1398
my_trades_info_t::my_trade_info_t my_trades_info_t::my_trade_info_t::construct(const flatjson::fjson &json) {
    assert(json.is_valid());

    assert("unimplemented" == nullptr);
}
Please, help to fix.
For now  I just commented this code.

Regards, Alexpitek.

**Comment by niXman** [comment]
hi,

fixed: https://github.com/niXman/binapi/commit/0d091c65f43323d19272c9be9342b34d31e943b3

please test and close.

**Comment by alexpitek** [comment]
Thank you.
