### ISSUE TITLE
How can I get result of compiling..?

### ISSUE THREAD

**Issue by qkrrudgh30** [niXman/binapi#34]
Hi, I want to know how I can get the "result" something like console printing..

First of all, I run "cmake CMakeList" on my cmd. (Windows10)

and, this does compile well..

What should I do next..?

If you don't mind, may I ask your manual for this source compiling?

Thank you for your opensource!
regards, qkrrudgh30

**Comment by niXman** [comment]
hi,

for example just go to `examples/websockets` directory, then `cmake .` and `websockets.exe`
