### ISSUE TITLE
 json.hpp: No such file or directory

### ISSUE THREAD

**Issue by nikolay-code** [niXman/binapi#4]
src/errors.cpp|13|fatal error: json.hpp: No such file or directory|
the next command will help you:
sudo apt install nlohmann-json-dev

Also I have the next linker options with CodeBlocks:
-lboost_system -lboost_thread -lpthread
-lssl -lcrypto -I/usr/include/openssl/

**Comment by niXman** [comment]
no need to add `src/errors.cpp` to project sources because it is not in [CMakeLists](https://github.com/niXman/binapi/blob/master/CMakeLists.txt#L40)

there is an unfinished idea in this file, just ignore it.

**Comment by niXman** [comment]
so no need to install `nlohmann-json-dev` too.
