### ISSUE TITLE
need help. 'examples/websockets' compiles without trouble, but '(a)synchronous' do not

### ISSUE THREAD

**Issue by Andrej-VB** [niXman/binapi#40]
After git cloning, and running **cmake** . & **make** functions, I successfully ran the _examples/websockets_ part. 
However, after doing the same with _synchronous_ & _asynchronous_ examples, I get the following error after running **make** in cmd: 

> Consolidate compiler generated dependencies of target synchronous

> [ 11%] Linking CXX executable synchronous

> /usr/bin/ld: CMakeFiles/synchronous.dir/home/pcname/binapi3/binapi/src/websocket.cpp.o: in function `binapi::ws::websockets::impl::start_channel<std::function<bool (char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, binapi::ws::market_ticker_t)> >(char const*, char const*, std::function<bool (char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, binapi::ws::market_ticker_t)>)::{lambda(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, unsigned long)#1}::operator()(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, unsigned long) const':

> websocket.cpp:(.text._ZZN6binapi2ws10websockets4impl13start_channelISt8functionIFbPKciNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_15market_ticker_tEEEEEPvS6_S6_T_ENKUlS6_iSC_S6_mE_clES6_iSC_S6_m[_ZZN6binapi2ws10websockets4impl13start_channelISt8functionIFbPKciNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_15market_ticker_tEEEEEPvS6_S6_T_ENKUlS6_iSC_S6_mE_clES6_iSC_S6_m]+0xbe): undefined reference to `binapi::rest::is_api_error(flatjson::fjson const&)'

> api.cpp:(.text._ZN6binapi4rest3api4impl4postISt8functionIFbPKciNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ping_tEEESt5tupleIJS6_iSC_SD_EESD_EENS1_6resultIT1_EEbS6_N5boost5beast4http4verbERKSt16initializer_listISt4pairIS6_NSL_7variantImJS6_EEEEET_[_ZN6binapi4rest3api4impl4postISt8functionIFbPKciNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ping_tEEESt5tupleIJS6_iSC_SD_EESD_EENS1_6resultIT1_EEbS6_N5boost5beast4http4verbERKSt16initializer_listISt4pairIS6_NSL_7variantImJS6_EEEEET_]+0x66a): undefined reference to `binapi::rest::is_api_error(flatjson::fjson const&)'

> /usr/bin/ld: websocket.cpp:(.text._ZZN6binapi2ws10websockets4impl13start_channelISt8functionIFbPKciNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_15market_ticker_tEEEEEPvS6_S6_T_ENKUlS6_iSC_S6_mE_clES6_iSC_S6_m[_ZZN6binapi2ws10websockets4impl13start_channelISt8functionIFbPKciNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_15market_ticker_tEEEEEPvS6_S6_T_ENKUlS6_iSC_S6_mE_clES6_iSC_S6_m]+0xef): undefined reference to `binapi::rest::construct_error[abi:cxx11](flatjson::fjson const&)'

These lines repeat about 100-200 times with minimal variance, and the exception ends with:

> collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/synchronous.dir/build.make:209: synchronous] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/synchronous.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

I will add the .txt file with the whole exception. 
The problem is probably due to my inexperience with coding, and I feel the solution is trivial, but I've been having troubles for a few days now and decided to reach out for help. If there is anything trivial I may be missing, I would be glad if you could at least point me in the right direction Sorry for clogging the Issues if this is not allowed here, and for any bad fromatting. 

I look forward to hearing from you. Thanks in advance!

[AndrejVB_binapi_issue.txt](https://github.com/niXman/binapi/files/6801023/AndrejVB_binapi_issue.txt)

**Comment by niXman** [comment]
hi,

im sorry, my bad :(

fixed.

please re-clone it.

and close this issue.

thanks!

**Comment by Andrej-VB** [comment]
Seeing this message a bit late. The code compiles without trouble now! :D
Thank you very much!

**Comment by Andrej-VB** [comment]
The code compiles without trouble now! I saw the message too late, so I didn't close the issue myself. :D
Thank you very much!
