### ISSUE TITLE
trades ws stream out of sync / time drift

### ISSUE THREAD

**Issue by chromafunk** [niXman/binapi#45]
frequency gets higher during event
![2021-09-29-151957_2560x1440_scrot](https://user-images.githubusercontent.com/3601695/135277938-4170014b-6076-4d5d-a0dd-5de43a730157.png)

stream gets totally out of sync shortly after ( trades time T was out of sync with Binance for close to 1  minute here already
![2021-09-29-152539_2560x1440_scrot](https://user-images.githubusercontent.com/3601695/135278084-50af682c-0c92-4f75-bcef-adc9f23cc519.png)

after a while, it seems that it starts getting past messages again, but the clock is already like 8 minutes out of sync and it doesn't recover
![2021-09-29-152814_2560x1440_scrot](https://user-images.githubusercontent.com/3601695/135278405-55b0e806-7ba3-437e-888c-5f6f75e0151c.png)

I simply instantiate a buffer with pre-initialized reserved size of 500 and each new message I pushback, then I delete the first when it exceeds the reserved value so to create this sequence, there is nothing complicated on the way I do it. I don't understand why this happens but it looks like it's from Binance's side or maybe from the implementation ? But I don't really know just yet. I have triple-checked everything locally and my hardware too

**Comment by chromafunk** [comment]
I have pretty fast fiber link and my software is running on dual xeon proliant servers, so this is not a matter of power or connection quality I believe

**Comment by niXman** [comment]
very strange...
can I look at the code?

**Comment by chromafunk** [comment]
mainly this 

```
class TradeBuffer
{
public:
    vector<double> tradespriceb;
    vector<double> tradesquantityb;
    vector<int> is_maker;
    vector<size_t> eventtimeb;
    int buffer_size;

    TradeBuffer(int const &buffer_size)
    {
        this->buffer_size = buffer_size;
        tradespriceb.reserve(buffer_size);
        tradesquantityb.reserve(buffer_size);
        is_maker.reserve(buffer_size);
    };

    void add_to_buffer(auto const &trades)
    {
        tradespriceb.push_back(double(trades.p));
        tradesquantityb.push_back(double(trades.q));
        eventtimeb.push_back(size_t(trades.E));
        is_maker.push_back(trades.m);
    }

    void check_buffer_size()
    {
        if (tradespriceb.size() >= 500)
        {
            tradespriceb.erase(tradespriceb.begin());
            tradesquantityb.erase(tradesquantityb.begin());
            eventtimeb.erase(eventtimeb.begin());
            is_maker.erase(is_maker.begin());
        }
    }
};
```
```
TradeBuffer buff(500);

const char *marketc = market.c_str();

boost::asio::io_context ioctx;
binapi::ws::websockets ws{ioctx, "stream.binance.com", "9443"};

ws.trade(marketc, [&](const char *fl, int ec, std::string emsg, auto trades)
         {
             if (ec)
             {
                 std::cerr << "subscribe book error: fl=" << fl << ", ec=" << ec << ", emsg=" << emsg << std::endl;

                 return false;
             }

             buff.add_to_buffer(trades);
             buff.check_buffer_size();

             return true;
         });

ioctx.run();
```

**Comment by chromafunk** [comment]
just a commnent, the clock I'm printing is not trades.E but trades.T, which is the trade time. The trades.E vector is in the buffer but I'm not using it currently, so that is irrelevant to the issue.

**Comment by niXman** [comment]
hmm... I need to think about this...

but I have a suggestion: try to profile your code using valgrind+callgrind, and then provide collected data here, I'll analyze it.

**Comment by chromafunk** [comment]
sure, I'll post you soon

**Comment by chromafunk** [comment]
[valgrind.txt](https://github.com/niXman/binapi/files/7253083/valgrind.txt)
[callgrind.txt](https://github.com/niXman/binapi/files/7253084/callgrind.txt)

Seems that I have a leak when I use the Yaml parser to parse markets from a yaml file, but the rest I don't know how to identify ... maybe you can shed some light ... thank you !

**Comment by niXman** [comment]
thanks, but I need the file located at `/home/xavier/spectre/build/callgrind.out.13278` ;)

**Comment by chromafunk** [comment]
[callgrind.out.13278.log](https://github.com/niXman/binapi/files/7253156/callgrind.out.13278.log)
here :) thanks

**Comment by chromafunk** [comment]
meanwhile I will run two procs, one with graphing and one without on the same market and see if that's the actual culprit, but I'm pretty sure I already tested this a week ago and it also happened. It's hard to catch because it seems to happen when frequency gets very high ( sell-off or pumps ) but I will keep on posting here

**Comment by chromafunk** [comment]
-

**Comment by chromafunk** [comment]
The drift is def caused by the graphing app. Sorry and thank you very much
