### ISSUE TITLE
One boost asio context for ws and rest

### ISSUE THREAD

**Issue by kv-gits** [niXman/binapi#5]
Is it possible to use one asio context for ws and rest? I am trying but streams not responce

**Comment by niXman** [comment]
hi,

sure you can:
ioctx: https://github.com/niXman/binapi/blob/master/main.cpp#L62
ws: https://github.com/niXman/binapi/blob/master/main.cpp#L63
and rest: https://github.com/niXman/binapi/blob/master/main.cpp#L66

**Comment by niXman** [comment]
just, in that case, avoid using the synchronous way of using rest.

**Comment by niXman** [comment]
or, just, provide the example please.

**Comment by kv-gits** [comment]
Thanks! No problem with ctx. Seems I have another issue

**Comment by niXman** [comment]
=)
