### ISSUE TITLE
m_map and return type of functions.

### ISSUE THREAD

**Issue by deepanshnagaria** [niXman/binapi#50]
The map used: m_map is a map from void\* (shared_ptr.get()) to a weak pointer, also you are returning void\* from the functions, is there any specific reason for not returning a wek_ptr or shared_ptr of the WebSocket itself to the caller? This will provide socket-level functionalities(write/read) to the caller and also instead of a map you could have used a set/list of weak_ptrs and on unsubscribe, there will be no lookup involved, directly the caller gives unsubscribe(weak_ptr) instead of void* followed by map lookup.

Similarly for cleanup: iterating over a list and checking lock, if not acquired, we clear.

As a whole, wanted to know the reason behind using shared_ptr.get() and void*

**Comment by niXman** [comment]
done: https://github.com/niXman/binapi/commit/422365e8ae6b7f806d31ef0910862dd919ade537

please close the issue.

**Comment by deepanshnagaria** [comment]
hi @niXman thanks for the help, just one more thing, the whole idea of keeping this set is just to keep a track of active websocket connections, isn't it? If we don't pass shared pointer around anymore, the ws is dead, we are closing it with stop() and throwing an error and then cleaning its entry from the map/set.
Unsubscribe can work by checking if we can take a lock on that WebSocket ptr, right? Just for unsubscribe all, we are keeping this? And remove dead ws is just to reduce the size of this set?

**Comment by niXman** [comment]
> Unsubscribe can work by checking if we can take a lock on that WebSocket ptr, right?

right.

> Just for unsubscribe all, we are keeping this? And remove dead ws is just to reduce the size of this set?

correct.

**Comment by deepanshnagaria** [comment]
wouldn't it be better we just maintain a list of weak_ptrs and in the destructor of WebSockets check for lock and close? Unsubscribe_all should be mandatory to call na? otherwise, we will leave opened files.

**Comment by niXman** [comment]
yes, this problem can be solved in that way too, but in that case checking the presence of each specific handle will have linear complexity, or abandon such a check completely...

**Comment by niXman** [comment]
redone using `boost::intrusive::set` instead of `std::set` because it allows to avoid one extra memory allocation for the set's node.

https://github.com/niXman/binapi/commit/7f1751ce1ad72702f76779e8deabc85e5a3d945b

@deepanshnagaria please close
