### ISSUE TITLE
Setting and using the project

### ISSUE THREAD

**Issue by emadmohd211** [niXman/binapi#51]

**Comment by niXman** [comment]
hi,

sure, I'll try to do it this week.

**Comment by perdpg** [comment]
Could you please also add some document about flatjson?

**Comment by niXman** [comment]
@perdpg what do you mean?
flatjson is used in the private part, how could you have questions about it?

**Comment by perdpg** [comment]
We need to use flatjson to parse the websocket results and extract the numeric values, right? So it is part of user interface, not private.

**Comment by niXman** [comment]
> We need to use flatjson to parse the rest/websocket results and extract the numeric values, right?

no

**Comment by perdpg** [comment]
Could you show how to convert the historical kline data in json format to array in C?

**Comment by niXman** [comment]
could you point me to where exactly do you see historical kline data in JSON format?

**Comment by perdpg** [comment]
Never mind. After reading your code again, I found that what I asked for is already implemented. Nice work!

**Comment by niXman** [comment]
@emadmohd211 

did you try to compile the examples?
could you describe the difficulties you faced?
