### ISSUE TITLE
subscribe trades error

### ISSUE THREAD

**Issue by perdpg** [niXman/binapi#52]
I am running it with just a BTCUSDT trade stream. For two times, it errors out with the following message after about 2.5 days:

subscribe trades error: fl=/home/tmp/binapi/src/websocket.cpp(197), ec=1, emsg=stream truncated

Any suggestion?

**Comment by niXman** [comment]
what continuous interval of time was the subscription active?

**Comment by perdpg** [comment]
Here is the code:

int main() {
    boost::asio::io_context ioctx;

    binapi::ws::websockets ws{
         ioctx
        ,"stream.binance.com"
        ,"9443"
    };

    ws.trade("BTCUSDT",
        [](const char *fl, int ec, std::string emsg, auto trades) {
            if ( ec ) {
                std::cerr << "subscribe trades error: fl=" << fl << ", ec=" << ec << ", emsg=" << emsg << std::endl;

                return false;
            }

            std::cout << trades.t << " " << trades.T << " " << trades.p << " " << trades.q << std::endl;

            return true;
        }
    );

    boost::asio::steady_timer timer2{ioctx, std::chrono::steady_clock::now() + std::chrono::hours(24*7)};
    timer2.async_wait([&ws](const auto &/*ec*/){
        std::cout << "async unsubscribing all" << std::endl;
        ws.async_unsubscribe_all();
    });

    ioctx.run();

    return EXIT_SUCCESS;
}

**Comment by niXman** [comment]
https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#general-wss-information

> A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark

**Comment by niXman** [comment]
please close.

**Comment by perdpg** [comment]
What's the recommended way to deal with the 24 hours limitation?

**Comment by niXman** [comment]
some time before the 24 hour mark, create another connection, sync subscriptions, and switch to the second connection. and so on in a circle.

**Comment by perdpg** [comment]
Got it. Do you have plan to implement it inside this project?

**Comment by niXman** [comment]
no

**Comment by niXman** [comment]
@perdpg please close
