### ISSUE TITLE
subscribe books error

### ISSUE THREAD

**Issue by mg10100** [niXman/binapi#53]
Hi!
After the websockets running between 3 and 5 minutes the errors shows as follow:
subscribe books error: fl=/home/mg/binapi-master/src/websocket.cpp(195), ec=2, emsg=End of file

Sometimes, the last message is:
subscribe books error: fl=/home/mg/binapi-master/src/websocket.cpp(195), ec=104, emsg=Connection reset by peer
Maybe I'm doing something wrong, or forgot something.
Is the pong send automatically ?

My code is:
int main() {
    boost::asio::io_context ioctx;

    binapi::ws::websockets ws{
         ioctx
        ,"stream.binance.com"
        ,"9443"
    };

    auto books_handler = ws.books(
        [](const char *fl, int ec, std::string emsg, auto books) {
            if ( ec ) {
                std::cerr << "subscribe books error: fl=" << fl << ", ec=" << ec << ", emsg=" << emsg << std::endl;

                return false;
            }

            std::cout << "books: " << books << std::endl;
            return true;
        }
    );

    boost::asio::steady_timer timer1{ioctx, std::chrono::steady_clock::now() + std::chrono::hours(20)};
    timer1.async_wait([&ws, books_handler](const auto &/*ec*/){
        std::cout << "async unsubscribing books_handler: " << books_handler << std::endl;
        ws.async_unsubscribe(books_handler);
    });
    ioctx.run();

    return EXIT_SUCCESS;
}

**Comment by niXman** [comment]
hi,

I think the same as https://github.com/niXman/binapi/issues/43

**Comment by niXman** [comment]
@mg10100 please close
