### ISSUE TITLE
Trying to get it to work

### ISSUE THREAD

**Issue by Foec** [niXman/binapi#54]
Could you provide little more help to compile this in visual studio. I added the library includes and src:s to visual studio and still get shit ton of error messages, i know its me not your program

**Comment by niXman** [comment]
hi,

were you able to compile any of the examples?

**Comment by Foec** [comment]
Hey, i was not able, do i need to open the library at Cmake first? Also is this linux only or windows too

Also, does PK mean private key, and SK public key?

I'm sorry im first time trying to compile 3rd party library =D

**Comment by niXman** [comment]
I have no experience with visual studio but I think it should support CMake?
if yes - please show the output.
if no - I think I can't help with this...

**Comment by niXman** [comment]
> Also, does PK mean private key, and SK public key?

SK - secret key, so PK - public

**Comment by Foec** [comment]
i will try to work it out, if i cant i will post output here, anyway thank you very much =)
