### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Sr-316** [niXman/binapi#56]
How do you implement this package once cloning? Sorry.. pretty new to c++.. 
using Windows 11 Pro, but can use linux as well..

**Comment by niXman** [comment]
just check any CMakeLists file in one of example project and add the required files/options to your own project.

**Comment by Sr-316** [comment]
so if i wanted to use one of the examples, would I move that specific examples' CMakeLists.txt and main.cpp to the project root folder (overwriting the current ones) and build my project in the root folder?

**Comment by Sr-316** [comment]
or is the API built completely then imported into a seperate project that is being built (utilizing the structure of the examples as it's main.cpp / CMakeLists.txt

**Comment by Sr-316** [comment]
sorry.  gotcha. Ty and TY for your work and for sharing it. very much.
