### ISSUE TITLE
Doubts installation

### ISSUE THREAD

**Issue by joaoguariglia** [niXman/binapi#57]
Good afternoon,

Is it possible to do a step by step compilation of your solution? I'm from IT I understand the technical terms, but I'm infrastructure oriented, I wanted to do this build on a Debian, but I don't know where to start after I do # git clone....

**Comment by niXman** [comment]
> but I don't know where to start after I do # git clone....

please look at that CMakeLists: https://github.com/niXman/binapi/blob/master/examples/asynchronous-user_data/CMakeLists.txt

pay attention to these lines:
1) definitions: https://github.com/niXman/binapi/blob/master/examples/asynchronous-user_data/CMakeLists.txt#L8
2) headers: https://github.com/niXman/binapi/blob/master/examples/asynchronous-user_data/CMakeLists.txt#L23
3) sources: https://github.com/niXman/binapi/blob/master/examples/asynchronous-user_data/CMakeLists.txt#L38
4) linked libraries: https://github.com/niXman/binapi/blob/master/examples/asynchronous-user_data/CMakeLists.txt#L64
