### ISSUE TITLE
Missing filter type for exchange_info type

### ISSUE THREAD

**Issue by red-angry-bird** [niXman/binapi#58]
Hi niXman,
on 2022-04-13 binance announced a new filter type: TRAILING_DELTA (see: https://binance-docs.github.io/apidocs/spot/en/#filters).

This type is not known for exchange_info_t, leading to the error:
`default: assert("bad filterType" == nullptr);`

**Comment by niXman** [comment]
hi,

will do, thanks!

**Comment by niXman** [comment]
done: https://github.com/niXman/binapi/commit/ffc613513354e05fbc6b294789911ed97ec8277b

tested locally.

please close.

**Comment by red-angry-bird** [comment]
Fast as always - thx!
I want to test it myself and will close afterwards, will do it in the next days.

**Comment by niXman** [comment]
another part of changes according filters: https://github.com/niXman/binapi/commit/7b3138e3d72b26f7ebd59244a6e651488ffe5adf

just some of refactoring...
