### ISSUE TITLE
Hope not insane request

### ISSUE THREAD

**Issue by chromafunk** [niXman/binapi#59]
I hope you are doing fine and abundant. 

Do you think there is a remote chance we can get a C++ Kucoin lib ?

Thank you very much

**Comment by niXman** [comment]
hi,

could you explain please?

**Comment by chromafunk** [comment]
hi Nixman ! I was talking about integrating Kucoin in binapi, since they use a close to identical API : 
https://docs.kucoin.com/#general

Kucoin is the main competitor to Binance now and they have a good reputation. Adding it would add another source of liquidity and access to certain coins that are not in Binance.
