### ISSUE TITLE
how do we deal with a websocket disconnect ?

### ISSUE THREAD

**Issue by chromafunk** [niXman/binapi#61]
so I got a `subscribe book error: binapi/src/websocket.cpp(195) ec=1, emsg = stream truncated` error after a couple of days connected,
how do you normally deal with such error and can we auto-reconnect somehow ? 

Thanks !

**Comment by niXman** [comment]
https://github.com/niXman/binapi/issues/52

**Comment by chromafunk** [comment]
Thanks, solved it by creating an operator that controls the processes and switches them
