### ISSUE TITLE
Exchange_info bad filter error

### ISSUE THREAD

**Issue by DontUseeMe** [niXman/binapi#62]
When compiling in debug mode, calling `exchange_info()` fails because `Assertion failed: "bad filterType" == nullptr` It started to happen today. I am not sure on what changes binance made to filters or other reasons.

**Comment by niXman** [comment]
hi,

could you please set up a breakpoint on this line(https://github.com/niXman/binapi/blob/master/src/types.cpp#L610) and when it triggers please show the value of the `filter.filterType` string.

thanks!

**Comment by DontUseeMe** [comment]
Hi, it says `PERCENT_PRICE_BY_SIDE`

**Comment by niXman** [comment]
@DontUseeMe 

hi, 

this is strange but I can't confirm this because I can't see `PERCENT_PRICE_BY_SIDE` filter in response for `exchange_info()` request...
but yes, I agree that filter was added into the changelog (https://binance-docs.github.io/apidocs/spot/en/#change-log) at `2022-02-22`. hmm...

**Comment by niXman** [comment]
done: https://github.com/niXman/binapi/commit/b628e50d4a75e94eb67b40b94a070f3af3dc6039

could you please test and confirm?


best!

**Comment by DontUseeMe** [comment]
yes, now fixed, thanks
