### ISSUE TITLE
websocket stream growing delay 

### ISSUE THREAD

**Issue by ibpjbl** [niXman/binapi#65]
I'm using websockets::book, and some calls take a while. I've recently discovered that new events don't replace each other but pile up. For clarity I just wrote a program with callback function like sleep(10s). Passed orders' sequence in such case isn't different from the one I get if I just output info and immediately return. It seems like processing orders' in such way is risky because you never know how far behind are you, and I'd like to know is there a way to make new events replace each other while the callback function is working.

**Comment by niXman** [comment]
the code works as it should and it works correctly.
using asynchronous callbacks and in the same time using sleeps or heavy computing in those callbacks - you turn the async API into synchronous =)

just do you need it another thread. but even in this case your algorithms must run faster than the events from binance come.

**Comment by ibpjbl** [comment]
i can't take responsibility for the frequency of new events and sometimes heavy computing is convenient, but i didn't think about using threads on myself. thanks
