### ISSUE TITLE
Compilation issues on WIndows

### ISSUE THREAD

**Issue by masimo12358** [niXman/binapi#66]
Trying to compile this with Visual Studio, there are some errors:

C:\binapi\include\binapi\flatjson.hpp(350,16): error C4146: unary minus operator applied to unsigned type, result still unsigned

Also:

1>------ Build started: Project: Proj, Configuration: Debug x64 ------
1>api.cpp
1>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
1>- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
1>- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
1>Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).

Maybe it's better to replace flatjson with Boost ptree?

**Comment by niXman** [comment]
> C:\binapi\include\binapi\flatjson.hpp(350,16): error C4146: unary minus operator applied to unsigned type, result still unsigned

very strange... maybe the compiler suggests overflow...

>1>------ Build started: Project: Proj, Configuration: Debug x64 ------
>1>api.cpp
>1>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
>1>- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
>1>- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
>1>Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).

this is smth windows specific, but I don't have windows.

> Maybe it's better to replace flatjson with Boost ptree?

why? because of MSVC behavior?

just try this fix:
`return -static_cast<To>(conv_to<typename std::make_unsigned<To>::type>(ptr, len - 1));`

**Comment by niXman** [comment]
@masimo12358 please close if you have no more questions.
