### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by klemenpeganc** [niXman/binapi#7]
Hi, any chance you could provide the changes needed to compile this on windows?

**Comment by niXman** [comment]
hi,

I have not tried to compile this code for windows, but I think there should be no problems because there is nothing platform-dependent in the code...

**Comment by klemenpeganc** [comment]
Hi, thanks for your answer. The problem occurs when linking additional libraries:
target_link_libraries(
    ${PROJECT_NAME}
    z
    crypto
    ssl
    pthread
)

What would the windows equivalent be of this?

**Comment by niXman** [comment]
`z` - zlib
`crypto` and `ssl` - openssl
`pthread` - just ignore it

**Comment by klemenpeganc** [comment]
this worked, I managed to get it to build.
However, now every function call results in: 
**can't dereference value-initialized vector iterator**

Call stack:
![image](https://user-images.githubusercontent.com/23028734/102498904-d9407500-407a-11eb-965d-24dbff6ffd76.png)

**Comment by niXman** [comment]
hmm... could you provide me the sample code that leads to this error?

**Comment by klemenpeganc** [comment]
`binapi::rest::api api(
         ioctx
        ,"api.binance.com"
        ,"443"
        , API_KEY
        , PRIVATE_KEY
        ,10000
    );

auto server_time = api.server_time();`

It crashes in flatjson.hpp, line 1451: m_end = &(*m_storage->end());
Contents of m_storage:
![image](https://user-images.githubusercontent.com/23028734/102501803-207c3500-407e-11eb-9275-ce314c4059c0.png)

**Comment by niXman** [comment]
which compiler are you using?

**Comment by klemenpeganc** [comment]
MSVC 19.22.27905.0

**Comment by niXman** [comment]
I don't have access to the Windows machine, but I'll try to figure it out...

**Comment by klemenpeganc** [comment]
Thanks, appreciate it! I will try using Clang in the meantime. I will let you know how it goes

**Comment by klemenpeganc** [comment]
Just wanted to let you know, that it fully works using MSVC in Release mode.

**Comment by niXman** [comment]
fixed: https://github.com/niXman/flatjson/commit/617d4cbaf6b1aea1e1ec47a1799952f8197dccb4

please confirm.

**Comment by repane4229** [comment]
@klemenpeganc can you let me know how you built this on windows
with setting up all the libs?
Thanks

**Comment by klemenpeganc** [comment]
I used vcpkg for the libraries and my CMakeLists.txt file looks like this:
```cmake_minimum_required(VERSION 3.2)
project(binapi)

set(CMAKE_CXX_STANDARD 14)
include(path/to/vcpkg.cmake)
find_package(ZLIB REQUIRED)
find_package(OpenSSL REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
add_definitions(
    -UNDEBUG
    -DDTF_HEADER_ONLY
    -D__FLATJSON__CHILDS_TYPE=std::uint32_t
    -D__FLATJSON__VLEN_TYPE=std::uint32_t
)

include_directories(
    ./include
)

include_directories("path/to/boost/folder")
link_directories("path/to/boost/libs")

set(BINAPI_HEADERS
    binapi/api.hpp
    binapi/flatjson.hpp
    binapi/dtf.hpp
    binapi/double_type.hpp
    binapi/invoker.hpp
    binapi/io_state.hpp
    binapi/message.hpp
    binapi/pairslist.hpp
    binapi/reports.hpp
    binapi/tools.hpp
    binapi/types.hpp
    binapi/websocket.hpp
)

set(BINAPI_SOURCES
    src/api.cpp
    src/io_state.cpp
    src/pairslist.cpp
    src/reports.cpp
    src/tools.cpp
    src/types.cpp
    src/websocket.cpp
)

add_executable(
    ${PROJECT_NAME}
    #
    main.cpp
    #
    ${BINAPI_SOURCES}
)


target_link_libraries(
    ${PROJECT_NAME}
    ZLIB::ZLIB
    OpenSSL::SSL
   OpenSSL::Crypto
)
