### ISSUE TITLE
Build issue on Mac ARM 64

### ISSUE THREAD

**Issue by kailashgautham** [niXman/binapi#72]
Hi, I seem to be facing this issue while trying to build my project in CLion on MacBook - apologies in advance if it's something silly that's preventing my build

FAILED: stockwise 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/stockwise.dir/backend/binapi/examples/asynchronous/main.cpp.o CMakeFiles/stockwise.dir/backend/binapi/examples/asynchronous-user_data/main.cpp.o CMakeFiles/stockwise.dir/backend/binapi/examples/synchronous/main.cpp.o CMakeFiles/stockwise.dir/backend/binapi/examples/synchronous-user_data/main.cpp.o CMakeFiles/stockwise.dir/backend/binapi/examples/websockets/main.cpp.o CMakeFiles/stockwise.dir/backend/binapi/include/binapi/dtf.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/api.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/enums.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/errors.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/pairslist.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/reports.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/tools.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/types.cpp.o CMakeFiles/stockwise.dir/backend/binapi/src/websocket.cpp.o CMakeFiles/stockwise.dir/backend/binapi/main.cpp.o CMakeFiles/stockwise.dir/backend/binance_data.cpp.o -o stockwise   && :
Undefined symbols for architecture arm64:
  "_BIO_ctrl", referenced from:
      boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const in api.cpp.o
      boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const in websocket.cpp.o
  "_BIO_ctrl_pending", referenced from:
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in api.cpp.o
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in websocket.cpp.o
  "_BIO_free", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
      boost::asio::ssl::detail::engine::~engine() in api.cpp.o
      boost::asio::ssl::detail::engine::~engine() in websocket.cpp.o
  "_BIO_new_bio_pair", referenced from:
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in api.cpp.o
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in websocket.cpp.o
  "_BIO_new_file", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_BIO_read", referenced from:
      boost::asio::ssl::detail::engine::get_output(boost::asio::mutable_buffer const&) in api.cpp.o
      boost::asio::ssl::detail::engine::get_output(boost::asio::mutable_buffer const&) in websocket.cpp.o
  "_BIO_write", referenced from:
      boost::asio::ssl::detail::engine::put_input(boost::asio::const_buffer const&) in api.cpp.o
      boost::asio::ssl::detail::engine::put_input(boost::asio::const_buffer const&) in websocket.cpp.o
  "_ERR_clear_error", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in api.cpp.o
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in websocket.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
  "_ERR_get_error", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      binapi::rest::api::impl::sync_post(char const*, boost::beast::http::verb, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in api.cpp.o
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in api.cpp.o
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in api.cpp.o
      binapi::rest::api::impl::on_resolve(boost::system::error_code const&, std::__1::unique_ptr<boost::beast::http::message<true, boost::beast::http::basic_string_body<char, std::__1::char_traits<char>, std::__1::allocator<char>>, boost::beast::http::basic_fields<std::__1::allocator<char>>>, std::__1::default_delete<boost::beast::http::message<true, boost::beast::http::basic_string_body<char, std::__1::char_traits<char>, std::__1::allocator<char>>, boost::beast::http::basic_fields<std::__1::allocator<char>>>>>, boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>) in api.cpp.o
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in websocket.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
      ...
  "_ERR_lib_error_string", referenced from:
      boost::asio::error::detail::ssl_category::message(int) const in api.cpp.o
      boost::asio::error::detail::ssl_category::message(int) const in websocket.cpp.o
  "_ERR_reason_error_string", referenced from:
      boost::asio::error::detail::ssl_category::message(int) const in api.cpp.o
      boost::asio::error::detail::ssl_category::message(int) const in websocket.cpp.o
  "_EVP_DigestInit_ex", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_DigestVerifyFinal", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_DigestVerifyInit", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_DigestVerifyUpdate", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_MD_CTX_free", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_MD_CTX_new", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_PKEY_free", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_EVP_sha256", referenced from:
      binapi::rest::hmac_sha256(char const*, unsigned long, char const*, unsigned long) in api.cpp.o
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_HMAC", referenced from:
      binapi::rest::hmac_sha256(char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_PEM_read_bio_PUBKEY", referenced from:
      binapi::rest::verify_signature(unsigned char const*, unsigned long, char const*, unsigned long) in api.cpp.o
  "_SSL_CTX_ctrl", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
  "_SSL_CTX_free", referenced from:
      boost::asio::ssl::context::~context() in api.cpp.o
      boost::asio::ssl::context::~context() in websocket.cpp.o
  "_SSL_CTX_get_default_passwd_cb_userdata", referenced from:
      boost::asio::ssl::context::~context() in api.cpp.o
      boost::asio::ssl::context::~context() in websocket.cpp.o
  "_SSL_CTX_get_ex_data", referenced from:
      boost::asio::ssl::context::~context() in api.cpp.o
      boost::asio::ssl::context::~context() in websocket.cpp.o
  "_SSL_CTX_new", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
  "_SSL_CTX_set_default_passwd_cb_userdata", referenced from:
      boost::asio::ssl::context::~context() in api.cpp.o
      boost::asio::ssl::context::~context() in websocket.cpp.o
  "_SSL_CTX_set_ex_data", referenced from:
      boost::asio::ssl::context::~context() in api.cpp.o
      boost::asio::ssl::context::~context() in websocket.cpp.o
  "_SSL_CTX_set_options", referenced from:
      boost::asio::ssl::context::set_options(long, boost::system::error_code&) in api.cpp.o
      boost::asio::ssl::context::set_options(long, boost::system::error_code&) in websocket.cpp.o
  "_SSL_accept", referenced from:
      boost::asio::ssl::detail::engine::do_accept(void*, unsigned long) in api.cpp.o
      boost::asio::ssl::detail::engine::do_accept(void*, unsigned long) in websocket.cpp.o
  "_SSL_connect", referenced from:
      boost::asio::ssl::detail::engine::do_connect(void*, unsigned long) in api.cpp.o
      boost::asio::ssl::detail::engine::do_connect(void*, unsigned long) in websocket.cpp.o
  "_SSL_ctrl", referenced from:
      binapi::rest::api::impl::sync_post(char const*, boost::beast::http::verb, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in api.cpp.o
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in api.cpp.o
      binapi::rest::api::impl::on_resolve(boost::system::error_code const&, std::__1::unique_ptr<boost::beast::http::message<true, boost::beast::http::basic_string_body<char, std::__1::char_traits<char>, std::__1::allocator<char>>, boost::beast::http::basic_fields<std::__1::allocator<char>>>, std::__1::default_delete<boost::beast::http::message<true, boost::beast::http::basic_string_body<char, std::__1::char_traits<char>, std::__1::allocator<char>>, boost::beast::http::basic_fields<std::__1::allocator<char>>>>>, boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>) in api.cpp.o
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in websocket.cpp.o
      binapi::ws::websocket::async_connect(boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>, std::__1::function<bool (char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char const*, unsigned long)>, std::__1::shared_ptr<binapi::ws::websocket>) in websocket.cpp.o
  "_SSL_free", referenced from:
      boost::asio::ssl::detail::engine::~engine() in api.cpp.o
      boost::asio::ssl::detail::engine::~engine() in websocket.cpp.o
  "_SSL_get_error", referenced from:
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in api.cpp.o
      boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*) in websocket.cpp.o
  "_SSL_get_ex_data", referenced from:
      boost::asio::ssl::detail::engine::~engine() in api.cpp.o
      boost::asio::ssl::detail::engine::~engine() in websocket.cpp.o
  "_SSL_get_shutdown", referenced from:
      boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const in api.cpp.o
      boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const in websocket.cpp.o
  "_SSL_new", referenced from:
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in api.cpp.o
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in websocket.cpp.o
  "_SSL_read", referenced from:
      boost::asio::ssl::detail::engine::do_read(void*, unsigned long) in api.cpp.o
      boost::asio::ssl::detail::engine::do_read(void*, unsigned long) in websocket.cpp.o
  "_SSL_set_bio", referenced from:
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in api.cpp.o
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in websocket.cpp.o
  "_SSL_set_ex_data", referenced from:
      boost::asio::ssl::detail::engine::~engine() in api.cpp.o
      boost::asio::ssl::detail::engine::~engine() in websocket.cpp.o
  "_SSL_shutdown", referenced from:
      boost::asio::ssl::detail::engine::do_shutdown(void*, unsigned long) in api.cpp.o
      boost::asio::ssl::detail::engine::do_shutdown(void*, unsigned long) in websocket.cpp.o
  "_SSL_write", referenced from:
      boost::asio::ssl::detail::engine::do_write(void*, unsigned long) in api.cpp.o
      boost::asio::ssl::detail::engine::do_write(void*, unsigned long) in websocket.cpp.o
  "_TLS_client_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
  "_TLS_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
  "_TLS_server_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in api.cpp.o
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in websocket.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

The boost library works fine in my main class (I've included it in the outer-most CMakeList). Thank you!

**Comment by niXman** [comment]
hi,

according to the error message:
```
Undefined symbols for architecture arm64:
"_BIO_ctrl", referenced from:
boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const in api.cpp.o
boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const in websocket.cpp.o
```
there is no openssl libs available on your system.
