### ISSUE TITLE
 websockets::klines  support 1s  interval

### ISSUE THREAD

**Issue by qgbcs** [niXman/binapi#74]
`
websockets: /home/qgb/github/binapi/src/websocket.cpp:458: void* binapi::ws::websockets::klines(const char*, const char*, binapi::ws::websockets::on_kline_received_cb): Assertion `p != nullptr' failed.
`

add  websockets::klines to example

**Comment by niXman** [comment]
ah, will do now.

**Comment by niXman** [comment]
done: https://github.com/niXman/binapi/commit/87b55d6bf8ef3db77ff1e5e76f008d6a4262625f

please test and close.
